# Generated by Django 3.0.8 on 2020-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200723_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='content',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='created',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='title',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-07-24'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-07-24'),
        ),
    ]
