# Generated by Django 3.0.8 on 2020-07-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_fruits_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='title',
            new_name='info',
        ),
    ]
