# Generated by Django 3.0.8 on 2020-07-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200724_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
